# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'MissionControl' do
pod 'BEMSimpleLineGraph'
pod 'Charts'
pod 'SwiftyJSON'
end

target 'MissionControlTests' do

end

target 'MissionControlUITests' do

end

